name: Continuous Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # See https://github.com/actions/runner-images/issues/6185
      - name: Install gnome-keyring
        run: sudo apt-get update && sudo apt-get install -y gnome-keyring

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.4

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 2.1.3

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Test with pytest
        run: poetry run pytest ./tests
