name: Continuous Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # See https://github.com/actions/runner-images/issues/6185
      - name: Install keyring for python
        run: sudo apt install gnome-keyring

      - name: Set up Python 3.9.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.12

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.1

      - name: Install dependencies
        run: poetry install --with dev

      - name: Test with pytest
        run: poetry run pytest ./tests
