name: Upload Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # See https://github.com/actions/runner-images/issues/6185
      - name: Install keyring for python
        run: sudo apt install gnome-keyring

      - name: Set up Python 3.9.18
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.18

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.6.1

      - name: Install dependencies
        run: poetry install --with dev

      - name: Test with pytest
        run: poetry run pytest ./tests

      - name: Build package
        run: poetry build

      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        run: poetry publish
