name: Upload Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.2.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.4

      - name: Install dependencies
        run: poetry install --with dev

      - name: Confidence check (run tests)
        run: poetry run pytest tests

      - name: Build package
        run: poetry build

      - name: Publish package
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        run: poetry publish
